version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      root-development-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /plugins/rivers_ioc
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      plugin-dependencies:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /plugins/agent_compose_workflow
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      plugin-dependencies:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /plugins/agent_compose_strategy
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      plugin-dependencies:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /plugins/octobus
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      plugin-dependencies:
        patterns: ['*']
