import subprocess
import zipfile
from pathlib import Path

import pytest
import yaml

from scripts.build_release import build_release, validate_version
from scripts.discover_plugins import discover
from scripts.validate_plugins import scan_private_references, validate_plugin
from scripts.validate_runtime_requirements import dependency_lines


def test_discover_returns_sorted_plugins(tmp_path: Path) -> None:
    for name in ("zeta", "alpha"):
        plugin = tmp_path / "plugins" / name
        plugin.mkdir(parents=True)
        (plugin / "manifest.yaml").touch()
    assert [item["name"] for item in discover(tmp_path)] == ["alpha", "zeta"]


def test_private_reference_scan_covers_all_rfc1918_networks(tmp_path: Path) -> None:
    (tmp_path / "addresses.txt").write_text(
        "10.2.3.4 172.16.0.1 172.31.255.254 192.168.1.1 127.0.0.1 203.0.113.2",  # private-reference: allow -- scanner fixture.
        encoding="utf-8",
    )
    assert scan_private_references(tmp_path) == ["private IP found in addresses.txt"]


def test_private_reference_scan_allows_localhost(tmp_path: Path) -> None:
    (tmp_path / "localhost.txt").write_text("127.0.0.1 localhost", encoding="utf-8")
    assert scan_private_references(tmp_path) == []


def test_plugin_validation_requires_tool_parameter_human_description(tmp_path: Path) -> None:
    plugin = tmp_path / "plugins" / "demo"
    (plugin / "provider").mkdir(parents=True)
    (plugin / "tools").mkdir()
    for filename in (
        "main.py",
        "requirements.txt",
        "PRIVACY.md",
        "Taskfile.yml",
        "README.md",
        "CHANGELOG.md",
    ):
        (plugin / filename).touch()
    (plugin / "_assets").mkdir()
    (plugin / "_assets" / "icon.svg").touch()
    (plugin / "manifest.yaml").write_text(
        "name: demo\nauthor: chaitin\nversion: 1.0.0\n"
        "meta: {version: 1.0.0, minimum_dify_version: 1.15.0}\n"
        "plugins: {tools: [provider/demo.yaml]}\n",
        encoding="utf-8",
    )
    (plugin / "provider" / "demo.yaml").write_text("tools: [tools/demo.yaml]\n", encoding="utf-8")
    (plugin / "tools" / "demo.yaml").write_text(
        "parameters:\n  - {name: query, type: string, form: llm}\n", encoding="utf-8"
    )

    assert validate_plugin(tmp_path, {"name": "demo", "path": "plugins/demo"}) == [
        "demo: tool tools/demo.yaml parameter query missing human_description"
    ]


def test_agent_compose_clients_do_not_drift() -> None:
    root = Path(__file__).resolve().parents[1]
    workflow = root / "plugins/agent_compose_workflow/client/agent_compose.py"
    strategy = root / "plugins/agent_compose_strategy/client/agent_compose.py"
    assert workflow.read_bytes() == strategy.read_bytes()


@pytest.mark.parametrize(
    "declaration",
    [
        "plugins/agent_compose_strategy/strategies/dynamic_workflow.yaml",
        "plugins/agent_compose_workflow/tools/run_agent.yaml",
    ],
)
def test_agent_compose_query_uses_string_type(declaration: str) -> None:
    root = Path(__file__).resolve().parents[1]
    definition = yaml.safe_load((root / declaration).read_text(encoding="utf-8"))
    query = next(
        parameter for parameter in definition["parameters"] if parameter["name"] == "query"
    )

    assert query["type"] == "string"


def test_release_build_uses_version_without_modifying_sources(tmp_path: Path) -> None:
    root = Path(__file__).resolve().parents[1]
    original_manifests = {
        item["name"]: (root / item["path"] / "manifest.yaml").read_bytes()
        for item in discover(root)
    }

    def fake_runner(command: list[str], *, check: bool) -> subprocess.CompletedProcess[bytes]:
        assert check is True
        staging = Path(command[3])
        output = Path(command[5])
        with zipfile.ZipFile(output, "w") as archive:
            archive.write(staging / "manifest.yaml", "manifest.yaml")
        return subprocess.CompletedProcess(command, 0)

    packages = build_release(root, "1.2.3", tmp_path, "dify", runner=fake_runner)

    assert {package.name for package in packages} == {
        f"{name}-1.2.3.difypkg" for name in original_manifests
    }
    for package in packages:
        with zipfile.ZipFile(package) as archive:
            manifest = yaml.safe_load(archive.read("manifest.yaml"))
        assert manifest["version"] == "1.2.3"
        assert manifest["meta"]["version"] == "1.2.3"
    for item in discover(root):
        assert (root / item["path"] / "manifest.yaml").read_bytes() == original_manifests[
            item["name"]
        ]


@pytest.mark.parametrize("version", ["v1.2.3", "1.2", "1.2.3-rc1", "../1.2.3"])
def test_release_version_rejects_non_semver(version: str) -> None:
    with pytest.raises(ValueError, match="SemVer"):
        validate_version(version)


def test_requirements_validation_ignores_only_uv_command_header() -> None:
    exported = "# This file was autogenerated by uv via the following command:\n# command\na==1\n"
    assert dependency_lines(exported) == ["a==1\n"]


def test_requirements_validation_requires_uv_header() -> None:
    with pytest.raises(ValueError, match="uv export header"):
        dependency_lines("a==1\n")
