#!/usr/bin/env python3
"""Ensure packaged requirements are exact exports of each plugin's uv lockfile."""

from __future__ import annotations

import argparse
import difflib
import subprocess
from pathlib import Path

try:
    from .discover_plugins import discover
except ImportError:  # Executed directly as a script.
    from discover_plugins import discover


def dependency_lines(requirements: str) -> list[str]:
    lines = requirements.splitlines(keepends=True)
    if len(lines) < 2 or not lines[0].startswith("# This file was autogenerated by uv"):
        raise ValueError("requirements.txt is missing its uv export header")
    return lines[2:]


def exported_requirements(root: Path, plugin_path: str) -> str:
    result = subprocess.run(
        [
            "uv",
            "export",
            "--directory",
            plugin_path,
            "--frozen",
            "--no-dev",
            "--no-hashes",
            "--format",
            "requirements-txt",
        ],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def validate(root: Path) -> list[str]:
    errors: list[str] = []
    for plugin in discover(root):
        requirements_path = root / plugin["path"] / "requirements.txt"
        actual = dependency_lines(requirements_path.read_text(encoding="utf-8"))
        expected = dependency_lines(exported_requirements(root, plugin["path"]))
        if actual == expected:
            continue
        diff = "".join(
            difflib.unified_diff(
                actual,
                expected,
                fromfile=str(requirements_path.relative_to(root)),
                tofile="uv export",
            )
        )
        errors.append(f"{plugin['name']}: requirements.txt is stale\n{diff}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    errors = validate(args.root.resolve())
    if errors:
        print("\n".join(errors))
        return 1
    print("validated runtime requirements exports")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
